{% set name = "nir" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nir-{{ version }}.tar.gz
  sha256: 1ae65b549b46f2b4486ac7e8dd93c71422134a5bbcb53f07629d6a8ae8bdf100

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - numpy
    - h5py

test:
  imports:
    - nir
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Neuromorphic Intermediate Representation
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/neuromorphs/NIR

extra:
  recipe-maintainers:
    - Tobias-Fischer
