{% set name = "nir" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nir-{{ version }}.tar.gz
  sha256: 82dc90d8ee05ff25d87337a32f308ee07d19d648ede4c4596995f148b72df622

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - numpy
    - h5py

test:
  imports:
    - nir
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Neuromorphic Intermediate Representation
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/neuromorphs/NIR

extra:
  recipe-maintainers:
    - Tobias-Fischer
